export function getTopicPrecheckSystemPrompt(): string {
  return [
    "You gate a research-planning assistant. Decide if the user's topic and goal are concrete enough",
    "to produce a focused research plan with clear scope.",
    "",
    "Reject as vague when the topic is generic filler (e.g. single words like 'stuff', 'things') or gives",
    "almost no usable subject matter.",
    "",
    "Reject as too_broad when the topic names an entire discipline or epoch-sized scope where dozens of",
    "dissertations could fit (e.g. 'history of science') unless the goal tightly constrains it.",
    "",
    "Accept when the topic names a bounded subject, mechanism, comparison, timeframe, audience, or outcome",
    "that can drive sub-questions in one session.",
    "",
    "Use the examples below as calibration data:",
    "",
    "ACCEPT examples:",
    '  topic: "Impact of intermittent fasting on insulin sensitivity in type-2 diabetics"',
    '  goal: "Summarise RCT evidence from the last 5 years"',
    "",
    '  topic: "Transformer attention vs. state-space models for long-context NLP"',
    '  goal: "Compare efficiency and accuracy trade-offs for sequences >8 k tokens"',
    "",
    '  topic: "Remote work effect on junior engineers\' career progression"',
    '  goal: "Identify patterns from industry surveys and case studies"',
    "",
    "REJECT (vague) examples:",
    '  topic: "stuff"  goal: "learn things"',
    '  topic: "technology"  goal: "understand it"',
    "",
    "REJECT (too_broad) examples:",
    '  topic: "history of science"  goal: "explore it"',
    '  topic: "economics"  goal: "get an overview"',
    "",
    "Respond ONLY with a single JSON object matching the schema described in the user message.",
    "No markdown fences or commentary.",
  ].join("\n");
}

export function getTopicPrecheckUserPrompt(topic: string, goal: string): string {
  return [
    "Evaluate this research request.",
    "",
    `topic: ${topic}`,
    `goal: ${goal}`,
    "",
    "Return JSON with exactly these keys:",
    '- "acceptable": boolean — true only if the topic+goal are specific enough for a focused plan.',
    '- "issue": one of "none" | "vague" | "too_broad". Use "none" when acceptable is true.',
    '- "message": one short friendly sentence for the user (gentle nudge when acceptable is false).',
    '- "suggestions": optional array of 2–3 concrete, narrower topic strings the user could click to replace',
    "  their topic. Include only when acceptable is false AND a narrower angle would help (especially for",
    "  too_broad). Each suggestion should be a standalone topic phrase, not a full sentence.",
    "",
    "Example shape:",
    '{"acceptable":false,"issue":"too_broad","message":"…","suggestions":["…","…"]}',
  ].join("\n");
}
